### ISSUE TITLE
current season?

### ISSUE THREAD

**Issue by dailyherald** [jldbc/pybaseball#19]
Hi James. First, thank you! I'm playing with your package to learn more python and matplotlib.

However, I'm not getting current season information with standings, schedule_and_record and batting_stats_range.

Everything works fine with previous seasons though.

Thanks!

**Comment by jldbc** [comment]
Thanks for reporting these - I'll take a close look once data starts to populate for the new season and see what needs to be updated/refreshed. 

I know there's a bit of a reporting delay on some of these as well.

`schedule_and_record(2018, 'NYY')` gives me results for yesterday's game. This used to give the future schedule as well but it looks like fangraphs stopped providing that alongside season-to-date results. I'll need to either fix that or update the docs. 

`standings(2018)` is giving me results as of today - does it work for you?

I'll need to look into `batting_stats_range ` a little more, it could be due to a reporting delay or it could be due to site changes

**Comment by dailyherald** [comment]
Yes! records and standings are working, and batting_stats_range is working now too. Looks like it was just a delay in populating. I should have waited a bit longer before reporting. Thank you!
