### ISSUE TITLE
Splitting Statcast Requests into Multiple Queries

### ISSUE THREAD

**Issue by andersonfrailey** [jldbc/pybaseball#22]
Continuing a discussion that was started in issue #20, I think one of the ways we can solve the issues users are having when they try to run `statcast_pitcher` and `statcast_batter` queries over periods longer than about two months would be to break those queries up.

My general approach to this would be to first determine if a query is longer than some arbitrary maximum (probably around 60 days), then use some of the features in Python's datetime package to iterate over the user specified period in chunks calling the necessary function each time. This will result in a list of DataFrames returned by each function call and which can be bound together.

A secondary goal would be to run the queries in parallel, but I think that can wait until after this initial work is done.

I'm happy to work on adding this feature and would love to hear any feedback/ideas from others.

**Comment by jldbc** [comment]
Closing this out since the PR was merged. 

Your point on running these in parallel might not make a huge difference for these two functions, but it's definitely something I've considered for the `statcast` function where common queries require a larger number of requests. That might be a worthy project for another day.

Thanks!
