### ISSUE TITLE
Statcast spliting broken for number of days = 6*N+1

### ISSUE THREAD

**Issue by 903124** [jldbc/pybaseball#37]
When the number of day in date range is multiple of 6 plus 1 (i.e. 7, 13, 19...)  the last day cannot be import successfully
```
 FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  final_data = pd.concat(dataframe_list, axis=0)
```

**Comment by schorrm** [comment]
I think I have this figured out.
Statcast's endpoint sometimes misbehaves for identical dates.
Specifically, for some reason, it seems like it cannot take `player_type=pitcher` and `game_date_lt`/`game_date_gt` for a single day in the same. This then leads to failure to get a response for a small request where it expected to get one, and then concat fails. It will work, however, even if the dates are the same, if `player_type` isn't given there.
Example: the following link works.
`https://baseballsavant.mlb.com/statcast_search/csv?all=true&game_date_gt=2018-05-12&game_date_lt=2018-05-13&type=details`
This does not:
`https://baseballsavant.mlb.com/statcast_search/csv?all=true&player_type=pitcher&game_date_gt=2018-05-12&game_date_lt=2018-05-13&type=details`
So the bug is on the Statcast end.
So we could have a workaround by doing without the `player_type` -- I don't know what the ramifications of that are -- or maybe just ask for an extra day we don't need?

**Comment by jldbc** [comment]
looks like this is resolved - feel free to reopen if I'm misinterpreting

**Comment by 903124** [comment]
He identified the cause but the problem still exit

**Comment by schorrm** [comment]
I retried today and it seems to work now, I guess Statcast might have fixed the bug. If it's still broken for you, can you post code to replicate the bug?

**Comment by 903124** [comment]
I checked it seems to be fine now. Thanks!
