### ISSUE TITLE
scrape today's game pks?

### ISSUE THREAD

**Issue by pwu97** [jldbc/pybaseball#63]
i saw the post of the previous season's game id's csv file.

i was wondering if there was a function to scrape today's game pks? sort of hard to use the statcast function without knowing the game pks.

**Comment by jldbc** [comment]
I don't think there's anything specifically for that, but it's not too hard to grab a given date's ids from the statcast function's outputs. 

Something like this would give a fixed date's game_pk values:

`yesterday = statcast('2019-08-17')`
`game_ids = yesterday.game_pk.unique()`

Looking for today's ids using that source is a challenge because Baseball Savant isn't updating this data in real time. I'm not positive what their update schedule is, but today's data would be uploaded either sometime tonight or tomorrow morning. Does this help?
